export const complaintData = {
  'most_common_category': {
    'category': 'Operation/Personnel Violations',
    'allegation_name': 'Inventory Procedures',
  },
  'summary': 'summary',
  'incident_date': '2012-04-30',
  'involvements': [
    {
      'involved_type': 'investigator',
      'full_name': 'Peter Parker',
      'officer_id': 1,
    },
    {
      'involved_type': 'investigator',
      'full_name': 'Edward May',
      'officer_id': null,
    },
    {
      'involved_type': 'police_witness',
      'full_name': 'Patrick Boyle',
      'percentile_allegation': 96.9967,
      'percentile_trr': 67.9112,
      'percentile_allegation_civilian': 99.9817,
      'percentile_allegation_internal': 87.8280,
      'officer_id': 123,
    },
    {
      'involved_type': 'police_witness',
      'full_name': 'Corey Flagg',
      'percentile_trr': 12.5612,
      'percentile_allegation': 73.2128,
      'percentile_allegation_civilian': 99.9696,
      'percentile_allegation_internal': 99.6468,
      'officer_id': 8658,
    },
    {
      'involved_type': 'police_witness',
      'full_name': 'Charles Toussas',
      'percentile_trr': 15.3123,
      'percentile_allegation': 59.7657,
      'percentile_allegation_civilian': 99.9696,
      'percentile_allegation_internal': 99.6468,
      'officer_id': 1782,
    },
    {
      'involved_type': 'police_witness',
      'full_name': 'Kevin Osborn',
      'percentile_trr': 85.2355,
      'percentile_allegation': 33.2812,
      'percentile_allegation_internal': 99.6468,
      'percentile_allegation_civilian': 99.9696,
      'officer_id': 2859,
    },
    {
      'involved_type': 'police_witness',
      'full_name': 'Joe Parker',
      'percentile_trr': 54.12342,
      'percentile_allegation': 12.9273,
      'percentile_allegation_civilian': 99.9696,
      'percentile_allegation_internal': 99.6468,
      'officer_id': 8638,
    },
  ],
  'complainants': [
    {
      'gender': 'Male',
      'age': 57,
      'race': 'White',
    },
  ],
  'victims': [
    {
      'gender': 'Male',
      'age': 45,
      'race': 'Black',
    },
  ],
  'crid': '1053667',
  'point': {
    'lat': 41.846749,
    'lon': -87.685141,
  },
  'beat': '1034',
  'coaccused': [
    {
      'category': 'Excessive Force',
      'final_outcome': 'Unknown',
      'id': 6493,
      'final_finding': 'Sustained',
      'rank': 'Police Officer',
      'full_name': 'Donovan Markiewicz',
      'allegation_count': 10,
      'percentile_trr': 85.2355,
      'percentile_allegation': 33.2812,
      'percentile_allegation_internal': 99.6468,
      'percentile_allegation_civilian': 99.9696,
    },
    {
      'category': 'Excessive Force',
      'final_outcome': 'Unknown',
      'id': 234,
      'final_finding': 'Sustained',
      'rank': 'Police Officer',
      'full_name': 'John Foertsch',
      'allegation_count': 8,
      'percentile_trr': 65.2355,
      'percentile_allegation': 13.2812,
      'percentile_allegation_internal': 69.6468,
      'percentile_allegation_civilian': 59.9696,
    },
    {
      'category': 'Excessive Force',
      'final_outcome': 'Unknown',
      'id': 543,
      'final_finding': 'Sustained',
      'rank': 'Police Officer',
      'full_name': 'Kenneth Wojtan',
      'allegation_count': 5,
      'percentile_trr': 35.2355,
      'percentile_allegation': 33.2812,
      'percentile_allegation_internal': 29.6468,
      'percentile_allegation_civilian': 39.9696,
    },
  ],
  'location': 'Building',
  'address': '2459 WESTERN AVE, CHICAGO IL 60608',
};
