export const officer2235 = {
  'officer_id': 2235,
  'full_name': 'Kevin Osborn',
  active: true,
  'allegation_count': 104,
  badge: '8548',
  'historic_badges': ['8547', '8546'],
  'birth_year': 1957,
  'civilian_compliment_count': 4,
  'percentile_allegation': '99.8950',
  'percentile_trr': '0.0431',
  'date_of_appt': '1993-12-13',
  'date_of_resignation': '2017-01-15',
  'discipline_count': 1,
  gender: 'Male',
  'honorable_mention_count': 55,
  'honorable_mention_percentile': '85.8700',
  'major_award_count': 1,
  race: 'White',
  rank: 'Police Officer',
  'sustained_count': 1,
  'trr_count': 1,
  unit: {
    'unit_id': 6,
    description: 'District 005',
    'unit_name': '005',
  },
  percentiles: [
    {
      'officer_id': 2235,
      year: 2005,
      'percentile_allegation_civilian': '66.251',
      'percentile_allegation_internal': '0.023',
      'percentile_allegation': '41.001',
    },
    {
      'officer_id': 2235,
      year: 2006,
      'percentile_allegation_civilian': '66.251',
      'percentile_allegation_internal': '0.023',
      'percentile_trr': '44.7',
      'percentile_allegation': '41.001',
    },
    {
      'officer_id': 2235,
      year: 2007,
      'percentile_allegation_civilian': '0.022',
      'percentile_allegation_internal': '75.065',
      'percentile_trr': '0.046',
      'percentile_allegation': '31.201',
    },
  ],
};
export const officer27778 = { ...officer2235, 'officer_id': 27778, 'full_name': 'Carl Suchocki' };
export const officerNotEnoughPercentile = {
  'officer_id': 2234,
  'full_name': 'Not Enough Percentile Officer',
  active: true,
  'allegation_count': 104,
  badge: '8548',
  'historic_badges': ['8547', '8546'],
  'birth_year': 1957,
  'civilian_compliment_count': 4,
  'percentile_allegation': 99.895,
  'date_of_appt': '1993-12-13',
  'date_of_resignation': '2017-01-15',
  'discipline_count': 1,
  gender: 'Male',
  'honorable_mention_count': 55,
  'honorable_mention_percentile': 85.87,
  'major_award_count': 1,
  race: 'White',
  rank: 'Police Officer',
  'sustained_count': 1,
  'trr_count': 1,
  unit: {
    'unit_id': 6,
    description: 'District 005',
    'unit_name': '005',
  },
  percentiles: [
    {
      'officer_id': 2235,
      year: 2006,
      'percentile_allegation_civilian': '66.251',
      'percentile_trr': '44.7',
      'percentile_allegation': '41.001',
    },
    {
      'officer_id': 2235,
      year: 2007,
      'percentile_allegation_civilian': '0.022',
      'percentile_allegation_internal': '75.065',
      'percentile_allegation': '31.201',
    },
  ],
};

export const mockTimeline = [
  {
    'unit_name': '007',
    kind: 'AWARD',
    'unit_description': 'District 007',
    rank: 'Detective',
    date: '2006-03-01',
    'award_type': 'Honorable Mention',
  },
  {
    'unit_name': '007',
    kind: 'RANK_CHANGE',
    'unit_description': 'District 007',
    rank: 'Detective',
    date: '2006-02-28',
  },
  {
    'trr_id': 1,
    'unit_name': '007',
    kind: 'FORCE',
    taser: true,
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-12-17',
    'firearm_used': false,
  },
  {
    'trr_id': 2,
    'unit_name': '007',
    kind: 'FORCE',
    taser: false,
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-03-17',
    'firearm_used': false,
  },
  {
    'unit_name': '007',
    kind: 'UNIT_CHANGE',
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-01-07',
  },
  {
    'trr_id': 3,
    'unit_name': '153',
    kind: 'FORCE',
    taser: false,
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2004-12-17',
    'firearm_used': true,
  },
  {
    category: 'Illegal Search',
    'unit_name': '153',
    kind: 'CR',
    subcategory: 'Search Of Premise Without Warrant',
    crid: '294088',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2003-11-26',
    coaccused: 8,
    finding: 'Exonerated',
    outcome: 'No Action Taken',
    attachments: [
      {
        url: 'https://assets.documentcloud.org/documents/3518950/CRID-294088-CR.pdf',
        'preview_image_url': 'https://assets.documentcloud.org/documents/3518950/pages/CRID-294088-CR-p1-normal.gif',
        title: 'CRID 294088 CR',
        'file_type': 'document',
      },
      {
        url: 'https://player.vimeo.com/video/165206078',
        title: 'Video Clip',
        'file_type': 'video',
      },
      {
        url: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/262463136&amp',
        title: 'Audio Clip',
        'file_type': 'audio',
      },
    ],
  },
  {
    category: 'Criminal Misconduct',
    'unit_name': '153',
    kind: 'CR',
    subcategory: 'Theft',
    crid: '260131',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2003-02-17',
    coaccused: 4,
    finding: 'Sustained',
    outcome: 'No Action Taken',
    attachments: [
      {
        url: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/262463125&amp',
        title: 'Audio Clip',
        'file_type': 'audio',
      },
      {
        url: 'https://player.vimeo.com/video/165213573',
        title: 'Video Clip',
        'file_type': 'video',
      },
      {
        url: 'https://assets.documentcloud.org/documents/3518954/CRID-299780-CR.pdf',
        'preview_image_url': 'https://assets.documentcloud.org/documents/3518954/pages/CRID-299780-CR-p1-normal.gif',
        title: 'CRID 294088 CR',
        'file_type': 'document',
      },
    ],
  },
  {
    'unit_name': '153',
    kind: 'RANK_CHANGE',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2000-04-28',
  },
  {
    'unit_name': '153',
    kind: 'UNIT_CHANGE',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2000-04-28',
  },
  {
    kind: 'JOINED',
    'unit_description': 'Recruit Training Section',
    date: '2000-02-05',
  },
  {
    date: '2000-08-06',
    kind: 'LAWSUIT',
    rank: 'Detective',
    'unit_description': 'Recruit Training Section',
    'unit_name': '044',
    'case_no': '00-L-5230',
    'primary_cause': 'Excessive force, Racial epithets',
    attachments: [
      {
        title: 'Phone subject information organization off important.',
        url: 'https://assets.documentcloud.org/documents/6246754/CRID-1086093-CR-COPA-Summary-Report.pdf',
        'preview_image_url': 'https://assets.documentcloud.org/documents/6246754/pages/CRID.gif',
        'file_type': 'document',
        'id': '95637',
      },
    ],
  },
];

export const mockCoaccusals = [
  {
    id: 27778,
    'full_name': 'Carl Suchocki',
    'complaint_count': 10,
    'sustained_count': 5,
    'birth_year': 1975,
    race: 'White',
    gender: 'Male',
    rank: 'Police Officer',
    'percentile_trr': '49.1036',
    'percentile_allegation': '99.2525',
    'percentile_allegation_civilian': '99.2525',
    'percentile_allegation_internal': '79.9133',
    'coaccusal_count': 47,
  },
];

export const mockOfficerPageCms = {
  fields: [
    {
      name: 'triangle_description',
      type: 'rich_text',
      value: {
        entityMap: {},
        blocks: [{
          data: {},
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
          key: '2ff83',
          text: 'The corners of the triangle show the percentile score for this officer ' +
            'in each of three types of data: complaints from civilians, complaints from other officers, ' +
            'and self-reported uses of force.',
          type: 'unstyled',
        }],
      },
    },
    {
      name: 'triangle_sub_description',
      type: 'rich_text',
      value: {
        entityMap: {},
        blocks: [{
          data: {},
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
          key: '2ff84',
          text: 'If one corner of the black inner triangle is close to reaching the outer triangle, ' +
            'then this officer is named in a relatively high rate ' +
            'of incidents of that type compared with other officers.',
          type: 'unstyled',
        }],
      },
    },
    {
      name: 'scale_description',
      type: 'rich_text',
      value: {
        entityMap: {},
        blocks: [{
          data: {},
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
          key: '2ff85',
          text: 'If an officer’s percentile rank for civilian complaints is 99% ' +
            'then this means that they were accused in more civilian complaints per year than 99% of other officers.',
          type: 'unstyled',
        }],
      },
    },
    {
      name: 'scale_sub_description',
      type: 'rich_text',
      value: {
        entityMap: {},
        blocks: [{
          data: {},
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
          key: '2ff82',
          text: 'Civilian and internal complaint percentiles are based on data that is only available since 2000, ' +
            'use of force data is only available since 2004. ' +
            'The overall allegation count percentiles displayed on the officer profile page ' +
            'are calculated using data that reaches back to 1988.',
          type: 'unstyled',
        }],
      },
    },
    {
      name: 'no_data_explain_text',
      type: 'rich_text',
      value: {
        entityMap: {},
        blocks: [{
          data: {},
          depth: 0,
          entityRanges: [],
          inlineStyleRanges: [],
          key: '2ff86',
          text: 'There is not enough data to construct a radar graph for this officer.',
          type: 'unstyled',
        }],
      },
    },
  ],
};
