import { get } from 'actions/common/async-action';
import { v2Url } from 'utils/url-util';
import constants from 'constants';


export const LANDING_PAGE_CMS_API_URL = constants.LANDING_PAGE_CMS_API_ENDPOINT;

export const LANDING_PAGE_CMS_REQUEST_START = 'LANDING_PAGE_CMS_REQUEST_START';
export const LANDING_PAGE_CMS_REQUEST_SUCCESS = 'LANDING_PAGE_CMS_REQUEST_SUCCESS';
export const LANDING_PAGE_CMS_REQUEST_FAILURE = 'LANDING_PAGE_CMS_REQUEST_FAILURE';

export const requestCMS = () => (get(v2Url(LANDING_PAGE_CMS_API_URL), [
  LANDING_PAGE_CMS_REQUEST_START, LANDING_PAGE_CMS_REQUEST_SUCCESS, LANDING_PAGE_CMS_REQUEST_FAILURE]
)());

export const TOP_OFFICERS_BY_ALLEGATION_REQUEST_START = 'TOP_OFFICERS_BY_ALLEGATION_REQUEST_START';
export const TOP_OFFICERS_BY_ALLEGATION_REQUEST_SUCCESS = 'TOP_OFFICERS_BY_ALLEGATION_REQUEST_SUCCESS';
export const TOP_OFFICERS_BY_ALLEGATION_REQUEST_FAILURE = 'TOP_OFFICERS_BY_ALLEGATION_REQUEST_FAILURE';

export const requestTopOfficersByAllegation = () => get(
  v2Url(constants.TOP_OFFICERS_BY_ALLEGATION_ENDPOINT),
  [
    TOP_OFFICERS_BY_ALLEGATION_REQUEST_START,
    TOP_OFFICERS_BY_ALLEGATION_REQUEST_SUCCESS,
    TOP_OFFICERS_BY_ALLEGATION_REQUEST_FAILURE
  ]
)();

export const RECENT_ACTIVITIES_REQUEST_START = 'RECENT_ACTIVITIES_REQUEST_START';
export const RECENT_ACTIVITIES_REQUEST_SUCCESS = 'RECENT_ACTIVITIES_REQUEST_SUCCESS';
export const RECENT_ACTIVITIES_REQUEST_FAILURE = 'RECENT_ACTIVITIES_REQUEST_FAILURE';

export const requestRecentActivities = () => get(
  v2Url(constants.RECENT_ACTIVITIES_ENDPOINT),
  [
    RECENT_ACTIVITIES_REQUEST_START,
    RECENT_ACTIVITIES_REQUEST_SUCCESS,
    RECENT_ACTIVITIES_REQUEST_FAILURE
  ]
)();

export const NEW_DOCUMENT_ALLEGATIONS_REQUEST_START = 'NEW_DOCUMENT_ALLEGATIONS_REQUEST_START';
export const NEW_DOCUMENT_ALLEGATIONS_REQUEST_SUCCESS = 'NEW_DOCUMENT_ALLEGATIONS_REQUEST_SUCCESS';
export const NEW_DOCUMENT_ALLEGATIONS_REQUEST_FAILURE = 'NEW_DOCUMENT_ALLEGATIONS_REQUEST_FAILURE';

export const requestNewDocumentAllegations = () => get(
  v2Url(constants.NEW_DOCUMENT_ALLEGATIONS_ENDPOINT),
  [
    NEW_DOCUMENT_ALLEGATIONS_REQUEST_START,
    NEW_DOCUMENT_ALLEGATIONS_REQUEST_SUCCESS,
    NEW_DOCUMENT_ALLEGATIONS_REQUEST_FAILURE
  ]
)();


export const COMPLAINT_SUMMARIES_REQUEST_START = 'COMPLAINT_SUMMARIES_REQUEST_START';
export const COMPLAINT_SUMMARIES_REQUEST_SUCCESS = 'COMPLAINT_SUMMARIES_REQUEST_SUCCESS';
export const COMPLAINT_SUMMARIES_REQUEST_FAILURE = 'COMPLAINT_SUMMARIES_REQUEST_FAILURE';

export const requestComplaintSummaries = () => get(
  v2Url(constants.COMPLAINT_SUMMARIES_ENDPOINT),
  [
    COMPLAINT_SUMMARIES_REQUEST_START,
    COMPLAINT_SUMMARIES_REQUEST_SUCCESS,
    COMPLAINT_SUMMARIES_REQUEST_FAILURE
  ]
)();
