import { createAction } from 'redux-actions';

import { get, post, put } from 'actions/common/async-action';
import constants from 'constants';
import { v2Url } from 'utils/url-util';


export const PINBOARD_CREATE_REQUEST_START = 'PINBOARD_CREATE_REQUEST_START';
export const PINBOARD_CREATE_REQUEST_SUCCESS = 'PINBOARD_CREATE_REQUEST_SUCCESS';
export const PINBOARD_CREATE_REQUEST_FAILURE = 'PINBOARD_CREATE_REQUEST_FAILURE';

export const PINBOARD_UPDATE_REQUEST_START = 'PINBOARD_UPDATE_REQUEST_START';
export const PINBOARD_UPDATE_REQUEST_SUCCESS = 'PINBOARD_UPDATE_REQUEST_SUCCESS';
export const PINBOARD_UPDATE_REQUEST_FAILURE = 'PINBOARD_UPDATE_REQUEST_FAILURE';

export const PINBOARD_FETCH_REQUEST_START = 'PINBOARD_FETCH_REQUEST_START';
export const PINBOARD_FETCH_REQUEST_SUCCESS = 'PINBOARD_FETCH_REQUEST_SUCCESS';
export const PINBOARD_FETCH_REQUEST_FAILURE = 'PINBOARD_FETCH_REQUEST_FAILURE';

export const PINBOARD_COMPLAINTS_FETCH_REQUEST_START = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_START';
export const PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE';

export const PINBOARD_OFFICERS_FETCH_REQUEST_START = 'PINBOARD_OFFICERS_FETCH_REQUEST_START';
export const PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS = 'PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE = 'PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE';

export const PINBOARD_TRRS_FETCH_REQUEST_START = 'PINBOARD_TRRS_FETCH_REQUEST_START';
export const PINBOARD_TRRS_FETCH_REQUEST_SUCCESS = 'PINBOARD_TRRS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_TRRS_FETCH_REQUEST_FAILURE = 'PINBOARD_TRRS_FETCH_REQUEST_FAILURE';

export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE';
export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START';
export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS';

export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE';
export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START';
export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS';

export const ADD_ITEM_TO_PINBOARD = 'ADD_ITEM_TO_PINBOARD';
export const CHANGE_PINBOARD_TAB = 'CHANGE_PINBOARD_TAB';

export const REMOVE_ITEM_IN_PINBOARD_PAGE = 'REMOVE_ITEM_IN_PINBOARD_PAGE';

export const addItemToPinboard = createAction(ADD_ITEM_TO_PINBOARD);

export const removeItemInPinboardPage = createAction(REMOVE_ITEM_IN_PINBOARD_PAGE);

export const createPinboard = ({ officerIds, crids, trrIds }) => post(
  v2Url(constants.PINBOARDS_API_ENDPOINT),
  [
    PINBOARD_CREATE_REQUEST_START,
    PINBOARD_CREATE_REQUEST_SUCCESS,
    PINBOARD_CREATE_REQUEST_FAILURE,
  ]
)({ 'officer_ids': officerIds, crids: crids, 'trr_ids': trrIds });

export const updatePinboard = ({ id, title, officerIds, crids, trrIds }) => put(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/`,
  [
    PINBOARD_UPDATE_REQUEST_START,
    PINBOARD_UPDATE_REQUEST_SUCCESS,
    PINBOARD_UPDATE_REQUEST_FAILURE,
  ]
)({ title: title, 'officer_ids': officerIds, crids: crids, 'trr_ids': trrIds });

export const fetchPinboard = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/`,
  [
    PINBOARD_FETCH_REQUEST_START,
    PINBOARD_FETCH_REQUEST_SUCCESS,
    PINBOARD_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardComplaints = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/complaints/`,
  [
    PINBOARD_COMPLAINTS_FETCH_REQUEST_START,
    PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS,
    PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardOfficers = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/officers/`,
  [
    PINBOARD_OFFICERS_FETCH_REQUEST_START,
    PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS,
    PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardTRRs = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/trrs/`,
  [
    PINBOARD_TRRS_FETCH_REQUEST_START,
    PINBOARD_TRRS_FETCH_REQUEST_SUCCESS,
    PINBOARD_TRRS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardSocialGraph = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/social-graph/`,
  [
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START,
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS,
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardGeographicData = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/geographic-data/`,
  [
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START,
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS,
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE,
  ]
)();

export const changePinboardTab = createAction(CHANGE_PINBOARD_TAB);
