import { createAction } from 'redux-actions';
import { map, entries } from 'lodash';

import { get, post, put } from 'actions/common/async-action';
import constants from 'constants';
import { v2Url } from 'utils/url-util';


export const PINBOARD_CREATE_REQUEST_START = 'PINBOARD_CREATE_REQUEST_START';
export const PINBOARD_CREATE_REQUEST_SUCCESS = 'PINBOARD_CREATE_REQUEST_SUCCESS';
export const PINBOARD_CREATE_REQUEST_FAILURE = 'PINBOARD_CREATE_REQUEST_FAILURE';

export const PINBOARD_UPDATE_REQUEST_START = 'PINBOARD_UPDATE_REQUEST_START';
export const PINBOARD_UPDATE_REQUEST_SUCCESS = 'PINBOARD_UPDATE_REQUEST_SUCCESS';
export const PINBOARD_UPDATE_REQUEST_FAILURE = 'PINBOARD_UPDATE_REQUEST_FAILURE';

export const PINBOARD_FETCH_REQUEST_START = 'PINBOARD_FETCH_REQUEST_START';
export const PINBOARD_FETCH_REQUEST_SUCCESS = 'PINBOARD_FETCH_REQUEST_SUCCESS';
export const PINBOARD_FETCH_REQUEST_FAILURE = 'PINBOARD_FETCH_REQUEST_FAILURE';

export const PINBOARD_COMPLAINTS_FETCH_REQUEST_START = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_START';
export const PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE = 'PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE';

export const PINBOARD_OFFICERS_FETCH_REQUEST_START = 'PINBOARD_OFFICERS_FETCH_REQUEST_START';
export const PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS = 'PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE = 'PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE';

export const PINBOARD_TRRS_FETCH_REQUEST_START = 'PINBOARD_TRRS_FETCH_REQUEST_START';
export const PINBOARD_TRRS_FETCH_REQUEST_SUCCESS = 'PINBOARD_TRRS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_TRRS_FETCH_REQUEST_FAILURE = 'PINBOARD_TRRS_FETCH_REQUEST_FAILURE';

export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE';
export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START';
export const PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS = 'PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS';

export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE';
export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START';
export const PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS = 'PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS';

export const PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_START = 'PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_START';
export const PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_SUCCESS = 'PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_FAILURE = 'PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_FAILURE';

export const PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_START = 'PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_START';
export const PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_SUCCESS = 'PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_FAILURE = 'PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_FAILURE';

export const PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_START = 'PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_START';
export const PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_SUCCESS = 'PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_SUCCESS';
export const PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_FAILURE = 'PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_FAILURE';

export const PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_START = 'PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_START';
export const PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_SUCCESS = 'PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_SUCCESS';
export const PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_FAILURE = 'PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_FAILURE';

export const CHANGE_PINBOARD_TAB = 'CHANGE_PINBOARD_TAB';

export const ADD_OR_REMOVE_ITEM_IN_PINBOARD = 'ADD_OR_REMOVE_ITEM_IN_PINBOARD';
export const ADD_ITEM_IN_PINBOARD_PAGE = 'ADD_ITEM_IN_PINBOARD_PAGE';
export const REMOVE_ITEM_IN_PINBOARD_PAGE = 'REMOVE_ITEM_IN_PINBOARD_PAGE';
export const ORDER_PINBOARD = 'ORDER_PINBOARD';

export const addOrRemoveItemInPinboard = createAction(ADD_OR_REMOVE_ITEM_IN_PINBOARD);

export const removeItemInPinboardPage = createAction(REMOVE_ITEM_IN_PINBOARD_PAGE,
  item => ({ ...item, isPinned: true }));

export const addItemInPinboardPage = createAction(ADD_ITEM_IN_PINBOARD_PAGE,
  item => ({ ...item, isPinned: false }));

export const orderPinboard = createAction(ORDER_PINBOARD);

export const createPinboard = ({ officerIds, crids, trrIds }) => post(
  v2Url(constants.PINBOARDS_API_ENDPOINT),
  [
    PINBOARD_CREATE_REQUEST_START,
    PINBOARD_CREATE_REQUEST_SUCCESS,
    PINBOARD_CREATE_REQUEST_FAILURE,
  ]
)({ 'officer_ids': officerIds, crids: crids, 'trr_ids': trrIds });

export const updatePinboard = ({ id, title, officerIds, crids, trrIds }) => put(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/`,
  [
    PINBOARD_UPDATE_REQUEST_START,
    PINBOARD_UPDATE_REQUEST_SUCCESS,
    PINBOARD_UPDATE_REQUEST_FAILURE,
  ]
)({ title: title, 'officer_ids': officerIds, crids: crids, 'trr_ids': trrIds });

export const fetchPinboard = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/`,
  [
    PINBOARD_FETCH_REQUEST_START,
    PINBOARD_FETCH_REQUEST_SUCCESS,
    PINBOARD_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardComplaints = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/complaints/`,
  [
    PINBOARD_COMPLAINTS_FETCH_REQUEST_START,
    PINBOARD_COMPLAINTS_FETCH_REQUEST_SUCCESS,
    PINBOARD_COMPLAINTS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardOfficers = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/officers/`,
  [
    PINBOARD_OFFICERS_FETCH_REQUEST_START,
    PINBOARD_OFFICERS_FETCH_REQUEST_SUCCESS,
    PINBOARD_OFFICERS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardTRRs = id => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/trrs/`,
  [
    PINBOARD_TRRS_FETCH_REQUEST_START,
    PINBOARD_TRRS_FETCH_REQUEST_SUCCESS,
    PINBOARD_TRRS_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardSocialGraph = id => get(
  `${v2Url(constants.SOCIAL_GRAPH_API_ENDPOINT)}network/?pinboard_id=${id}`,
  [
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_START,
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_SUCCESS,
    PINBOARD_SOCIAL_GRAPH_FETCH_REQUEST_FAILURE,
  ]
)();

export const fetchPinboardGeographicData = id => get(
  `${v2Url(constants.SOCIAL_GRAPH_API_ENDPOINT)}geographic/?pinboard_id=${id}`,
  [
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START,
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS,
    PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE,
  ]
)();

export const changePinboardTab = createAction(CHANGE_PINBOARD_TAB);

const getWithPaginate = (pinboardRelevantAPI, types) => (id, params) => {
  const queryString = map(entries(params), ([key, val]) => `${key}=${val}`).join('&');
  const url = `${v2Url(constants.PINBOARDS_API_ENDPOINT)}${id}/${pinboardRelevantAPI}/?${queryString}`;

  return get(url, types)();
};

export const fetchPinboardRelevantDocuments = getWithPaginate(
  'relevant-documents',
  [
    PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_START,
    PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_SUCCESS,
    PINBOARD_RELEVANT_DOCUMENTS_FETCH_REQUEST_FAILURE,
  ]
);
export const fetchPinboardRelevantCoaccusals = getWithPaginate(
  'relevant-coaccusals',
  [
    PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_START,
    PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_SUCCESS,
    PINBOARD_RELEVANT_COACCUSALS_FETCH_REQUEST_FAILURE,
  ]
);
export const fetchPinboardRelevantComplaints = getWithPaginate(
  'relevant-complaints',
  [
    PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_START,
    PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_SUCCESS,
    PINBOARD_RELEVANT_COMPLAINTS_FETCH_REQUEST_FAILURE,
  ]
);

export const fetchLatestRetrievedPinboard = () => get(
  `${v2Url(constants.PINBOARDS_API_ENDPOINT)}latest-retrieved-pinboard/`,
  [
    PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_START,
    PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_SUCCESS,
    PINBOARD_LATEST_RETRIEVED_FETCH_REQUEST_FAILURE,
  ]
)();
