export const OFFICER_PAGE_TAB_NAMES = {
  TIMELINE: 'TIMELINE',
  MAP: 'MAP',
  COACCUSALS: 'COACCUSALS',
  ATTACHMENTS: 'DOCUMENTS',
};

export const RESET_TIME_LINE_FILTER = 'RESET_TIME_LINE_FILTER';

export const TAB_MAP = {
  coaccusals: OFFICER_PAGE_TAB_NAMES.COACCUSALS,
  documents: OFFICER_PAGE_TAB_NAMES.ATTACHMENTS,
  map: OFFICER_PAGE_TAB_NAMES.MAP,
};
