export const OFFICER_PAGE_TAB_NAMES = {
  TIMELINE: 'TIMELINE',
  COACCUSALS: 'COACCUSALS',
  ATTACHMENTS: 'ATTACHMENTS',
};

export const CHANGE_OFFICER_ID = 'CHANGE_OFFICER_ID';
export const CHANGE_OFFICER_TAB = 'CHANGE_OFFICER_TAB';
